// SPDX-License-Identifier: GPL-3.0-or-later
package app.kofipod.ui.theme

import androidx.compose.ui.graphics.Color

data class KofipodColors(
    val bg: Color,
    val bgSubtle: Color,
    val surface: Color,
    val surfaceAlt: Color,
    val border: Color,
    val borderStrong: Color,
    val text: Color,
    val textSoft: Color,
    val textMute: Color,
    val purple: Color,
    val purpleDeep: Color,
    val purpleSoft: Color,
    val purpleTint: Color,
    val pink: Color,
    val pinkSoft: Color,
    val success: Color,
    val warn: Color,
    val danger: Color,
    val isDark: Boolean,
)

val LightKofipodColors = KofipodColors(
    bg = Color(0xFFFBF8FF),
    bgSubtle = Color(0xFFF3ECFF),
    surface = Color(0xFFFFFFFF),
    surfaceAlt = Color(0xFFF6F0FF),
    border = Color(0xFFE7DDFB),
    borderStrong = Color(0xFFD5C4F4),
    text = Color(0xFF1A0B33),
    textSoft = Color(0xFF50407A),
    textMute = Color(0xFF8A7BB0),
    purple = Color(0xFF4B1E9E),
    purpleDeep = Color(0xFF2E0D6E),
    purpleSoft = Color(0xFF6D3BD2),
    purpleTint = Color(0xFFEADFFC),
    pink = Color(0xFFFF2E9A),
    pinkSoft = Color(0xFFFFD6EA),
    success = Color(0xFF10B981),
    warn = Color(0xFFF59E0B),
    danger = Color(0xFFE11D48),
    isDark = false,
)

val DarkKofipodColors = KofipodColors(
    bg = Color(0xFF0D0814),
    bgSubtle = Color(0xFF140C22),
    surface = Color(0xFF1A1128),
    surfaceAlt = Color(0xFF231636),
    border = Color(0xFF2D1F46),
    borderStrong = Color(0xFF3E2B60),
    text = Color(0xFFF2E9FF),
    textSoft = Color(0xFFBCA7E0),
    textMute = Color(0xFF7E6BA6),
    purple = Color(0xFFA881F5),
    purpleDeep = Color(0xFF7C4DEB),
    purpleSoft = Color(0xFFC4A6FF),
    purpleTint = Color(0xFF2A1A4A),
    pink = Color(0xFFFF6BB5),
    pinkSoft = Color(0xFF3A1930),
    success = Color(0xFF34D399),
    warn = Color(0xFFFBBF24),
    danger = Color(0xFFFB7185),
    isDark = true,
)
